// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type MetaState int32

const (
	MetaStateUninitialized   MetaState = 0
	MetaStateSectionsDefined MetaState = 1
	MetaStateSymbolsDefined  MetaState = 2
)

var EnumNamesMetaState = map[MetaState]string{
	MetaStateUninitialized:   "Uninitialized",
	MetaStateSectionsDefined: "SectionsDefined",
	MetaStateSymbolsDefined:  "SymbolsDefined",
}

var EnumValuesMetaState = map[string]MetaState{
	"Uninitialized":   MetaStateUninitialized,
	"SectionsDefined": MetaStateSectionsDefined,
	"SymbolsDefined":  MetaStateSymbolsDefined,
}

func (v MetaState) String() string {
	if s, ok := EnumNamesMetaState[v]; ok {
		return s
	}
	return "MetaState(" + strconv.FormatInt(int64(v), 10) + ")"
}
