FROM debian:testing-slim

RUN apt-get clean && apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends qemu-user qemu-user-static binutils

WORKDIR /app

EXPOSE 1234