# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VirtualSegment(object):
    __slots__ = ['_tab']

    # VirtualSegment
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VirtualSegment
    def Start(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # VirtualSegment
    def Size(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateVirtualSegment(builder, start, size):
    builder.Prep(8, 16)
    builder.PrependUint64(size)
    builder.PrependUint64(start)
    return builder.Offset()
