// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Emmutaler

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ROMMeta struct {
	_tab flatbuffers.Table
}

func GetRootAsROMMeta(buf []byte, offset flatbuffers.UOffsetT) *ROMMeta {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ROMMeta{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ROMMeta) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ROMMeta) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ROMMeta) BuildInfo(obj *BuildInfo) *BuildInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(BuildInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ROMMeta) LinkerInfo(obj *LinkerMeta) *LinkerMeta {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(LinkerMeta)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ROMMeta) Symbols(obj *Symbol, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ROMMeta) SymbolsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ROMMetaStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ROMMetaAddBuildInfo(builder *flatbuffers.Builder, buildInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(buildInfo), 0)
}
func ROMMetaAddLinkerInfo(builder *flatbuffers.Builder, linkerInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(linkerInfo), 0)
}
func ROMMetaAddSymbols(builder *flatbuffers.Builder, symbols flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(symbols), 0)
}
func ROMMetaStartSymbolsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ROMMetaEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
