// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Emmutaler

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Symbol struct {
	_tab flatbuffers.Table
}

func GetRootAsSymbol(buf []byte, offset flatbuffers.UOffsetT) *Symbol {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Symbol{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Symbol) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Symbol) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Symbol) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Symbol) Address() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Symbol) MutateAddress(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func SymbolStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SymbolAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func SymbolAddAddress(builder *flatbuffers.Builder, address uint64) {
	builder.PrependUint64Slot(1, address, 0)
}
func SymbolEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
